swagger: "2.0"
info:
  description: "This is a simple express server for managing clients"
  version: "1.0.0"
  title: "Client"
host: "localhost:3000"
basePath: "/api"
tags:
- name: "clients"
  description: "Managing clients"
schemes:
- "http"
paths:
  /delete/client/{id}:
    get:
      tags:
      - "clients"
      summary: "Find clients by id and delete"
      description: ""
      operationId: "findClientByIdAndDelete"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Client Id to be deleted"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful deleted"
        "404":
          description: "unrecognized client id"
  /delete/provider/{id}:
    get:
      tags:
      - "clients"
      summary: "Find provider by id and delete"
      description: ""
      operationId: "findProviderByIdAndDelete"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Provider Id to be deleted"
        required: true
        type: "number"
      responses:
        "200":
          description: "successful deleted a provider"
        "400":
          description: "Invalid ID"
  /providers:
    get:
      tags:
      - "clients"
      summary: "Returns all providers"
      description: "Returns an object of providers"
      operationId: "getProvider"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
        "500":
          description : " Internal server error"
  /add-provider:
    post:
      tags:
      - "clients"
      summary: "Add provider"
      description: ""
      operationId: "addProvider"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Provider to be saved"
        required: true
        schema:
          $ref: "#/definitions/Provider"
      responses:
        "200":
          description: "successfully added provider"
        "400":
          description: "Invalid Provider"
  /client/{id}:
    get:
      tags:
      - "clients"
      summary: "Find client by id"
      description: ""
      operationId: "getClientById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "clientId"
        in: "path"
        description: "ID of client that needs to be fetched"
        required: true
        type: "number"
      responses:
        "200":
          description: "successful created client"
        "400":
          description: "Invalid client ID "
        "404":
          description: "Client not found"
  /add-client:
    post:
      tags:
      - "clients"
      summary: "Add clients"
      description: ""
      operationId: "addClient"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created Client object"
        required: true
        schema:
          $ref: "#/definitions/Client"
      responses:
        "200":
          description: "successful created client"
        "500" : 
          description : Internal server error
  /update/client/{id}:
    post:
      tags:
      - "clients"
      summary: "Updates a client with it id"
      description: ""
      operationId: "FindAndUpdateClientById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in : "path"
        name : "id"
        description: "ID of client that needs to be fetched"
        required: true
        type: "number"
      - in: "body"
        name: "body"
        description: "Client field to be updated"
        required: true
        type: "object"
        schema:
          $ref: "#/definitions/Client"
      responses:
        "200":
          description: "successful updated client"
        "400":
          description : "Invalid ID"  
        "500":
          description : "Internal server error"  
  /client:
    get:
      tags:
      - "clients"
      summary: "Gets all client"
      description: ""
      operationId: "getClients"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        "200":
          description: "successful operation"
        "500":
          description: "Internal server error"

definitions:
  Table:
    type: "object"
    properties:
      client : 
        type: "array"
        items :
          type : "object"
          properties:
            name:
              type: "string"
            email:
              type: "string"
            phone:
              type: "integer"
            provider : 
              type: "array"
              items: 
                type : "object"
                properties :
                  id:
                    type: "integer"
                  name: 
                    type : "string"
      provider : 
        type : object
        properties : 
          id : number
          name : string
    xml:
      name: "Table"
  Provider:
    type: "object"
    properties:
      id:
        type: "number"
      provider:
        type: "string"
    xml:
      name: "Provider"
  Client:
    type: "object"
    properties:
      name:
        type: "string"
      email:
        type: "string"
      phone:
        type: "number"
      providerArray : 
        type: "array"
        items: 
          type : "object"
          properties :
            id:
              type: "string"
            name: 
              type : "string"        
    xml:
      name: "Client"
